apiVersion: v1
kind: Namespace
metadata:
  name: minio
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: minio
  namespace: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: emptydir
          emptyDir:
            sizeLimit: 3Gi
      initContainers:
        - name: init-bucket
          image: quay.io/prometheus/busybox
          command:
            - mkdir
            - /data/loki
          resources: {}
          volumeMounts:
            - name: emptydir
              mountPath: /data
      containers:
        - resources: {}
          name: minio
          env:
            - name: MINIO_ROOT_USER
              value: minio
            - name: MINIO_ROOT_PASSWORD
              value: miniopass101
          ports:
            - name: api
              containerPort: 9000
              protocol: TCP
            - name: console
              containerPort: 9001
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: emptydir
              mountPath: /data
          image: docker.io/minio/minio
          args:
            - server
            - /data
            - '--console-address'
            - ':9001'
            - '--address'
            - ':9000'
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
      
---

kind: Service
apiVersion: v1
metadata:
  name: s3
  namespace: minio
spec:
  selector:
    app: minio
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: api
    - name: console
      protocol: TCP
      port: 9001
      targetPort: console
